announce:
  slack:
    enabled: true
    message_template: ":tada: tenv {{.Tag}} is available! See what's new here - https://github.com/tofuutils/tenv/releases/tag/{{.Tag}}"
    channel: "#tofuutils"
    username: "tofuutils-notifications"
    icon_emoji: ""
    icon_url: ""
    blocks: []
    attachments: []

  telegram:
    enabled: true
    chat_id: -4020097127
    message_template: "🎉 tenv {{ mdv2escape .Tag}} is available{{ mdv2escape '!' }} See what is new here - https://github.com/tofuutils/tenv/releases/tag/{{ mdv2escape .Tag}}"
    parse_mode: HTML
