# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

project_name: tenv
version: 1

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - id: tenv
    binary: tenv
    main: ./cmd/tenv

    env:
      - CGO_ENABLED=0

    goos:
      - linux
      - windows
      - darwin
      - freebsd
      - openbsd
      - solaris

    goarch:
      - "386"
      - amd64
      - arm
      - arm64

  - id: tofu
    binary: tofu
    main: ./cmd/tofu

    env:
      - CGO_ENABLED=0

    goos:
      - linux
      - windows
      - darwin
      - freebsd
      - openbsd
      - solaris

    goarch:
      - "386"
      - amd64
      - arm
      - arm64

  - id: terraform
    binary: terraform
    main: ./cmd/terraform

    env:
      - CGO_ENABLED=0

    goos:
      - linux
      - windows
      - darwin
      - freebsd
      - openbsd
      - solaris

    goarch:
      - "386"
      - amd64
      - arm
      - arm64

release:
  name_template: "Release {{.Tag}}"

changelog:
  use: github-native

archives:
  - format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{- .Os }}_{{- .Arch }}"

nfpms:
  - file_name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Arch }}'
    maintainer: 'https://github.com/dvaumoron'
    homepage: https://github.com/tofuutils/tenv
    description: >-
      tenv help manage several version of OpenTofu (https://opentofu.org) and Terraform (https://www.terraform.io/),
      tenv is the managing command and tofu and terraform are proxy commands.
    license: "Apache-2.0"
    formats:
      - deb
      - rpm
      - apk
    bindir: /usr/bin
    section: default
    contents:
      - src: ./LICENSE
        dst: /usr/share/doc/tenv/copyright
        file_info:
          mode: 0444
    rpm:
      signature:
        key_file: "{{ if index .Env \"GPG_KEY_FILE\"  }}{{.Env.GPG_KEY_FILE}}{{ end }}"
    deb:
      signature:
        key_file: "{{ if index .Env \"GPG_KEY_FILE\"  }}{{.Env.GPG_KEY_FILE}}{{ end }}"

brews:
  - repository:
      owner: tofuutils
      name: homebrew-tap
    folder: Formula
    homepage: https://github.com/tofuutils/tenv
    description: OpenTofu and Terraform version manager (inspired by tofuenv, written in Go)
    license: "Apache-2.0"
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
