# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

project_name: gotofuenv
version: 1

before:
  hooks:
    - go mod tidy

builds:
  - id: gotofuenv
    binary: gotofuenv
    main: ./cmd/gotofuenv

    env:
      - CGO_ENABLED=0

    goos:
      - linux
      - windows
      - darwin
      - freebsd
      - openbsd
      - solaris

    goarch:
      - "386"
      - amd64
      - arm
      - arm64

  - id: tofu
    binary: tofu
    main: ./cmd/tofu

    env:
      - CGO_ENABLED=0

    goos:
      - linux
      - windows
      - darwin
      - freebsd
      - openbsd
      - solaris

    goarch:
      - "386"
      - amd64
      - arm
      - arm64

release:
  name_template: "Release {{.Tag}}"

archives:
  - format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{- .Os }}_{{- .Arch }}"

nfpms:
  - file_name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Arch }}'
    maintainer: 'https://github.com/dvaumoron'
    homepage: https://github.com/dvaumoron/gotofuenv
    description: >-
      gotofuenv help manage several version of OpenTofu (https://opentofu.org).
    license: "Apache-2.0"
    formats:
      - deb
      - rpm
      - apk
    bindir: /usr/bin
    section: default
    contents:
      - src: ./LICENSE
        dst: /usr/share/doc/gotofuenv/copyright
        file_info:
          mode: 0444
    rpm:
      signature:
        key_file: "{{ if index .Env \"GPG_KEY_FILE\"  }}{{.Env.GPG_KEY_FILE}}{{ end }}"
    deb:
      signature:
        key_file: "{{ if index .Env \"GPG_KEY_FILE\"  }}{{.Env.GPG_KEY_FILE}}{{ end }}"

changelog:
  use: github-native
