---
name: 'Release'

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

permissions:
  contents: write

jobs:
  goreleaser:
    name: 'Release the latest tag'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --clean -f ${{ vars.GORELEASER_CONFIG_PATH }}
        env:
          GITHUB_TOKEN: ${{ secrets.TENV_GITHUB_TOKEN }}
